[package]
name = "mosaic-landscape-runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#polars = {version = "0.37.0", features = ["lazy", "decompress"]}
bevy = "0.12.0"
bevy_rapier2d = "0.23.0"
